# Generated by Django 3.1.1 on 2020-09-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pos', models.TextField()),
                ('icon', models.URLField(max_length=1000)),
                ('colour', models.CharField(default='#000000', max_length=7)),
                ('text', models.TextField(default='This is a Dummy Text')),
            ],
        ),
    ]
