# Generated by Django 3.1.1 on 2020-09-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='pos',
            field=models.TextField(default='left', max_length=5),
        ),
    ]
