# Generated by Django 3.1.1 on 2020-10-09 04:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200930_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='icon',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='back'), size=None),
        ),
        migrations.AlterField(
            model_name='header',
            name='text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='text'), size=None),
        ),
        migrations.AlterField(
            model_name='header',
            name='title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='Title'), size=None),
        ),
    ]
