# Generated by Django 3.1.1 on 2020-10-11 11:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201011_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='icon',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='back'), size=None),
        ),
    ]
